# Generated by Django 4.2.6 on 2023-12-08 15:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_percentage', models.IntegerField(default=500, help_text='500 = 50%', validators=[django.core.validators.MaxValueValidator(950)])),
                ('name', models.CharField(help_text='Specific Item Name like Rusty Dagger, Sweet Bread or Leather Shirt', max_length=255, unique=True)),
                ('max_count', models.IntegerField(default=1, help_text='How many can be max found while Looting', validators=[django.core.validators.MinValueValidator(1)])),
                ('status_note', models.CharField(default='None', max_length=255)),
                ('weight_gram', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_gold', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEU', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rulesystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DSA4.1', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='lopine_items_app.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lopine_items_app.itemcondition'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lopine_items_app.itemplace'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lopine_items_app.itemtype'),
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lopine_items_app.language'),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lopine_items_app.itemrarity'),
        ),
        migrations.AddField(
            model_name='item',
            name='rulesystem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lopine_items_app.rulesystem'),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lopine_items_app.itemstatus'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='lopine_items_app.item')),
            ],
        ),
    ]
