# Generated by Django 4.2.6 on 2023-10-24 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_typ', models.CharField(choices=[('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Household', 'Household'), ('Nature_Matrial', 'Nature_Matrial')], default='Common Item', max_length=20)),
                ('gewichtung', models.IntegerField(default=1000)),
                ('name', models.CharField(max_length=255)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], default='Common', max_length=20)),
                ('max_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged')], default='Used', max_length=20)),
                ('status', models.CharField(choices=[('No Status', 'No_Status'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Unremarkable', max_length=20)),
                ('weight', models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app_loot.item')),
            ],
        ),
    ]
