# Generated by Django 4.2.6 on 2023-11-08 18:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_loot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gewichtung',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_typ',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.AddField(
            model_name='item',
            name='item_category_name',
            field=models.CharField(default='', help_text='Overall Category like Dagger, Bread or Shirt', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='item_place',
            field=models.CharField(choices=[('Loot', 'Loot'), ('Inventory', 'Inventory'), ('Both', 'Both')], default='Both', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Household', 'Household'), ('Nature_Material', 'Nature_Material'), ('Food', 'Food'), ('Lighting', 'Lighting'), ('Books', 'Books'), ('Eating Utensils', 'Eating Utensils'), ('Vehicles', 'Vehicles'), ('Vehicle Accessories', 'Vehicle Accessories'), ('Precision Mechanics', 'Precision Mechanics'), ('Long-range Weapons', 'Long-range Weapons'), ('Leisure Needs', 'Leisure Needs'), ('Spices', 'Spices'), ('Poisons', 'Poisons'), ('Medicinal Herbs', 'Medicinal Herbs'), ('Chains', 'Chains'), ('Clothing', 'Clothing'), ('Personal Care', 'Personal Care'), ('Ammunition', 'Ammunition'), ('Musical Instruments', 'Musical Instruments'), ('Melee Weapons', 'Melee Weapons'), ('Travel Supplies', 'Travel Supplies'), ('Armor Parts', 'Armor Parts'), ('Shields', 'Shields'), ('Parrying Weapons', 'Parrying Weapons'), ('Jewelry', 'Jewelry'), ('Stationery', 'Stationery'), ('Animals', 'Animals'), ('Pet Supplies', 'Pet Supplies'), ('Weapon Accessories', 'Weapon Accessories'), ('Tools', 'Tools'), ('Drinks', 'Drinks')], default='Weapon', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('DEU', 'DEU'), ('ENG', 'ENG')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='price_gold',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='item',
            name='rulesystem',
            field=models.CharField(choices=[('DSA4.1', 'DSA4.1'), ('DSA5', 'DSA5'), ('SR4', 'SR4'), ('SR5', 'SR5')], default='', max_length=20, verbose_name='Rulesystem (*)'),
        ),
        migrations.AddField(
            model_name='item',
            name='status_note',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_gram',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_percentage',
            field=models.IntegerField(default=500, help_text='500 = 50%', validators=[django.core.validators.MaxValueValidator(950)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged'), ('Rusted', 'Rusted'), ('Rotten', 'Rotten')], default='Used', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_count',
            field=models.IntegerField(default=1, help_text='How many can be max found while Looting', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Specific Item Name like Rusty Dagger, Sweet Bread or Leather Shirt', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('No Status', 'No Status'), ('Magical', 'Magical'), ('Karmal', 'Karmal'), ('Daemon', 'Daemon')], default='No Status', max_length=20),
        ),
        migrations.DeleteModel(
            name='ItemDetails',
        ),
        migrations.AddField(
            model_name='material',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='app_loot.item'),
        ),
        migrations.AddField(
            model_name='color',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='app_loot.item'),
        ),
    ]
