name: Django CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: start compose
      run: docker-compose up -d 

