name: Django CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: self-hosted
    timeout-minutes: 10
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.0]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
